### ISSUE TITLE
Error running swift build after Xcode 11.4 update

### ISSUE THREAD

**Issue by bofeizhu** [nerdishbynature/octokit.swift#101]
Error message:
`'OctoKit' ***/.build/checkouts/octokit.swift: error: target at '/ ***/.build/checkouts/octokit.swift' contains mixed language source files; feature not supported`

Blocking https://github.com/danger/swift/issues/327

**Comment by JohnnyTseng** [comment]
Having this issue too, are there any temporarily workarounds before this could be merged?

**Comment by AvdLee** [comment]
We're experiencing the same issue. I'm unsure how this is happening now. @bofeizhu do you have any idea?

**Comment by bofeizhu** [comment]
@AvdLee Yeah, I’ve submitted the PR to fix it #102. Still waiting for approval.

**Comment by pietbrauer** [comment]
Fixed in https://github.com/nerdishbynature/octokit.swift/releases/tag/0.10.1
