### ISSUE TITLE
Awaiting a new release

### ISSUE THREAD

**Issue by 417-72KI** [nerdishbynature/octokit.swift#122]
There are some PRs( #104 ~ #120 ) merged after [0.10.1](https://github.com/nerdishbynature/octokit.swift/releases/tag/0.10.1) released.

Is there any issue to release them?

**Comment by pietbrauer** [comment]
Would love to have #121 merged as well as it’s kind of critical. After that I’m fine with a new release.

**Comment by 417-72KI** [comment]
@pietbrauer 
It has been merged.
I want new release if no more problem🙏

**Comment by pietbrauer** [comment]
Sorry this took so long, version 0.11.0 is out.
