### ISSUE TITLE
How to disable caching?

### ISSUE THREAD

**Issue by Nikoloutsos** [nerdishbynature/octokit.swift#145]
I'm using `Octokit(config).pullRequests(owner: , repository: ) `
but if I make a change in my Github PR it doesn't fetch the new data when called.
Looks like it is caching the response for a while. 

Is there any way to disable this, and always fetch from a fresh api call?

**Comment by pietbrauer** [comment]
There was some discussion over here. Maybe this helps? https://github.com/nerdishbynature/RequestKit/pull/81#issuecomment-1024964772
