### ISSUE TITLE
List PRs in Private Repos

### ISSUE THREAD

**Issue by iUsmanN** [nerdishbynature/octokit.swift#155]
Hi,

I can't seem to get the PRs in private repos and get the error:

`Error Domain=com.nerdishbynature.octokit Code=404 "(null)" UserInfo={RequestKitErrorKey={
    "documentation_url" = "https://docs.github.com/rest/reference/pulls#list-pull-requests";
    message = "Not Found";
}}`

I've given the `repo` scope and feel it should be working. 

Any help would be appreciated!
Usman

**Comment by pietbrauer** [comment]
I was able to get this done with the repo scope

<img width="533" alt="image" src="https://user-images.githubusercontent.com/759730/204865420-cc345fce-9c11-48fc-85c3-ed84bb71c170.png">

```swift
do {
    let config = TokenConfiguration("your_token")
    let prs = try await Octokit(config).pullRequests(owner: "pietbrauer", repository: "my_private_repo", state: .all)
    print(prs.compactMap { $0.title })
} catch {
    print(error)
}
```
