### ISSUE TITLE
Add new API call for `Get repository content`

### ISSUE THREAD

**Issue by Nikoloutsos** [nerdishbynature/octokit.swift#161]
Hi 👋 ,
I want to get the raw contents of a file. I looked at the available API calls but [this](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content) was not found.

So I was thinking of me opening a PR about it.
What do you think?

**Comment by pietbrauer** [comment]
Sure, feel free to open a PR.

**Comment by aehlke** [comment]
@Nikoloutsos did you ever implement this?

**Comment by Nikoloutsos** [comment]
Hello @aehlke 👋 
I haven't done any progress on that

**Comment by pietbrauer** [comment]
Closed via #189
