### ISSUE TITLE
Support OSX via Cocoapods?

### ISSUE THREAD

**Issue by akring** [nerdishbynature/octokit.swift#31]
Will this great project support for OSX development via Cocoapods?
Really need it:)

**Comment by pietbrauer** [comment]
Not on my roadmap, but feel free to do a Pull Request ✌️

**Comment by akring** [comment]
OK,I will give it a try.
And before that,how can I add this to my OSX project manually?

**Comment by pietbrauer** [comment]
You could drop the Xcode project into your project and link the framework with your application. http://stackoverflow.com/questions/3352664/how-to-add-existing-frameworks-in-xcode-4

**Comment by akring** [comment]
OK,got it.
And thanks for your lightning response speed.Danke:)

**Comment by akring** [comment]
Er...still some problems,should I build this project first?or just clone it and drag the entire folder to my project?I'm a little confused.

**Comment by pietbrauer** [comment]
I addressed your features in #32
