### ISSUE TITLE
Support for Pull Requests + Issues

### ISSUE THREAD

**Issue by thomaspaulmann** [nerdishbynature/octokit.swift#33]
Do you have any plans to support Pull Requests and Issues? In particular, the topics that are related to a specific user, so f.e. all Pull Request of User XY.

**Comment by pietbrauer** [comment]
Not tomorrow, I am open for PullRequests! Have a look at the stuff other people contributed, it's really easy https://github.com/nerdishbynature/octokit.swift/pull/18

**Comment by thomaspaulmann** [comment]
Ok great... That's what I wanted to suppose to you. I'll contribute it. See you for the PR ;-)

**Comment by pietbrauer** [comment]
Sweeeet 🎉

**Comment by polok** [comment]
PR support: https://github.com/nerdishbynature/octokit.swift/pull/62

**Comment by superarts** [comment]
Any plan to add pagination support for `pulls` please?

**Comment by pietbrauer** [comment]
As we have [quite a few APIs for PullRequests](https://github.com/nerdishbynature/octokit.swift/blob/main/OctoKit/PullRequest.swift). I am closing this.

I'm always open for contributions if something is missing.
