### ISSUE TITLE
:/

### ISSUE THREAD

**Issue by AmirDaliri** [nerdishbynature/octokit.swift#54]
hi ,sorry bro but your app dont run :\

**Comment by pietbrauer** [comment]
@AmirDaliri Can you be a bit more specific?

**Comment by AmirDaliri** [comment]
yup ,first tnQ for for answer ,second -> 
![screen shot 1395-07-19 at 15 07 21](https://cloud.githubusercontent.com/assets/17800816/19234905/592aa956-8efb-11e6-8066-708e1190e4d1.png)

**Comment by pietbrauer** [comment]
Are you using Xcode 8?

**Comment by AmirDaliri** [comment]
no, i use xcode 7.3

**Comment by pietbrauer** [comment]
Please use Xcode 8 as this project is Swift 3.

**Comment by AmirDaliri** [comment]
ok tnx
