### ISSUE TITLE
Deprecated function in README.md

### ISSUE THREAD

**Issue by ashanaakh** [nerdishbynature/octokit.swift#65]
Hi there! First of all, thanks for awesome framework! 
```swift
func application(application: UIApplication, openURL url: NSURL,  sourceApplication: String?, annotation: AnyObject?) -> Bool
```
This function is deprecated, what should we use?

**Comment by pietbrauer** [comment]
Hey, please use it’s replacement:`open func open(_ url: URL, options: [String : Any] = [:],
  completionHandler completion: (@escaping (Bool) -> Swift.Void)`
