### ISSUE TITLE
Re-enable Podspec linting

### ISSUE THREAD

**Issue by ellneal** [nerdishbynature/octokit.swift#86]
This feature had to be disabled in https://github.com/nerdishbynature/octokit.swift/pull/85 in order to get the builds to pass, which were previously [timing out](https://travis-ci.org/nerdishbynature/octokit.swift/jobs/623351635#L464) when cloning the specs repo.

**Comment by pietbrauer** [comment]
CocoaPods is not in active maintenance anymore and I feel Swift Packages is the way to go. I am closing it for now until CocoaPods has a renaissance.
